version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: comments-api-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comments
